<h2>Question 1:

In [5]:
L = list(range(1,501))
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [32]:
s= list(range(0,501,21))
ans1 = s[1:501]
print(ans1)

[21, 42, 63, 84, 105, 126, 147, 168, 189, 210, 231, 252, 273, 294, 315, 336, 357, 378, 399, 420, 441, 462, 483]


In [29]:
mean = sum(ans1)/len(ans1)
print(mean)

252.0


In [34]:
0.25*len(ans1)

5.75

In [39]:
ans1[6]

147

In [38]:
0.50*len(ans1)

11.5

In [40]:
ans1[12]

273

In [41]:
0.75*len(ans1)

17.25

In [42]:
ans1[18]

399

<h3>Thus 25th, 50th and 75th percentile are 147, 273, 399.

In [54]:
num_lines = 0
num_words = 0
num_chars = 0
with open(r'C:\Users\Pari\Desktop\DataAnalysisPython\Lecture-03\ques2.txt', 'r') as f:
    for line in f:
        words = line.split()
        
        
        num_words += len(words)
        
        print(num_words)

309


<h3> Question 3


In [89]:
import glob, os
string = "User Not Found"
num_of_files = 0
os.chdir(r"C:\Users\Pari\Desktop\DataAnalysisPython\Lecture-03\jsons")
for file in glob.glob("*.json"):
    with open(os.path.join(root, file), 'r') as f:
        for line in f:
            if string in line:
                num_of_files = num_of_files + 1
                break
            else:
                continue
                
print (num_of_files)
                

877


In [112]:
import glob, os
D = {'user_id': None, 'present': None }
string = "User Not Found"
num_of_files = 0
os.chdir(r"C:\Users\Pari\Desktop\DataAnalysisPython\Lecture-03\jsons")
for file in glob.glob("*.json"):
    with open(os.path.join(root, file), 'r') as f:
        for line in f:
            if string in line:
                D= {'user_id' : None , 'present': 0}
                break
            else:
                D = {'user_id':None, 'present' : 1}
                continue

                

    
    print(D)
                


{'present': 0, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 0, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 1, 'user_id': None}
{'present': 1, 'user_id': None}
{'presen

<h3> Question 4